name: tests
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
        working-directory: ./backend
      - run: |
          npm run-script test
        working-directory: ./backend
